# Generated by Django 4.0.2 on 2022-09-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='name',
            field=models.CharField(choices=[('E-Mail', 'Ziel-E-Mail für Schadenmeldungen'), ('noreply-mail', 'noreply-E-Mail zum Versand der Schadenmeldung'), ('info-frontpage', 'info-frontpage')], max_length=50),
        ),
        migrations.AlterField(
            model_name='config',
            name='setting',
            field=models.CharField(max_length=400),
        ),
    ]
