# Generated by Django 4.0.2 on 2022-09-07 13:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0002_alter_config_name_alter_config_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='text',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
