# Generated by Django 4.0.2 on 2022-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0003_config_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='setting',
            field=models.CharField(max_length=30),
        ),
    ]
