# Generated by Django 4.0.2 on 2022-09-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool_settings', '0004_alter_config_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='setting',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
