# Generated by Django 3.2.3 on 2022-02-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buchungen',
            new_name='Buchung',
        ),
    ]
