# Generated by Django 3.2.3 on 2022-02-18 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0002_rename_buchungen_buchung'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buchung',
            name='stunde',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
