# Generated by Django 4.0.2 on 2022-03-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0003_auto_20220218_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='buchung',
            name='krzl',
            field=models.CharField(default='LOB', max_length=3),
            preserve_default=False,
        ),
    ]
