# Generated by Django 4.0.2 on 2022-03-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0004_buchung_krzl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buchung',
            new_name='Booking',
        ),
    ]
