# Generated by Django 4.0.2 on 2022-03-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0006_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='short_name',
            field=models.CharField(default='short name', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
