# Generated by Django 4.0.2 on 2022-03-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0007_room_short_name_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.CharField(default='Koffer_E', max_length=10),
            preserve_default=False,
        ),
    ]
