# Generated by Django 4.0.2 on 2022-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0008_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='lerngruppe',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=50),
        ),
    ]
