# Generated by Django 4.0.2 on 2022-04-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0010_room_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='iPad_01',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_02',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_03',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_04',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_05',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_06',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_07',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_08',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_09',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_10',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_11',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_12',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_13',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_14',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_15',
            field=models.CharField(default='|', max_length=40),
        ),
        migrations.AddField(
            model_name='booking',
            name='iPad_16',
            field=models.CharField(default='|', max_length=40),
        ),
    ]
