# Generated by Django 4.0.2 on 2022-05-09 14:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0011_booking_ipad_01_booking_ipad_02_booking_ipad_03_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='alert',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
