# Generated by Django 4.0.2 on 2022-04-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0011_booking_ipad_01_booking_ipad_02_booking_ipad_03_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_01',
            new_name='iPad_1',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_02',
            new_name='iPad_2',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_03',
            new_name='iPad_3',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_04',
            new_name='iPad_4',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_05',
            new_name='iPad_5',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_06',
            new_name='iPad_6',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_07',
            new_name='iPad_7',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_08',
            new_name='iPad_8',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_09',
            new_name='iPad_9',
        ),
    ]
