# Generated by Django 4.0.2 on 2022-05-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0012_room_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pen_01',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_02',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_03',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_04',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_05',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_06',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_07',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_08',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_09',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_10',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_11',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_12',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_13',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_14',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_15',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='pen_16',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_01',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_02',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_03',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_04',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_05',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_06',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_07',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_08',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_09',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_10',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_11',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_12',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_13',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_14',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_15',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_16',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
