# Generated by Django 4.0.2 on 2022-04-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0012_rename_ipad_01_booking_ipad_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_1',
            new_name='iPad_01',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_2',
            new_name='iPad_02',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_3',
            new_name='iPad_03',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_4',
            new_name='iPad_04',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_5',
            new_name='iPad_05',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_6',
            new_name='iPad_06',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_7',
            new_name='iPad_07',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_8',
            new_name='iPad_08',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='iPad_9',
            new_name='iPad_09',
        ),
    ]
