# Generated by Django 4.0.2 on 2022-04-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0013_rename_ipad_1_booking_ipad_01_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='iPad_01',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_02',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_03',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_04',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_05',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_06',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_07',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_08',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_09',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_10',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_11',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_12',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_13',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_14',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_15',
            field=models.CharField(default='0|0', max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='iPad_16',
            field=models.CharField(default='0|0', max_length=40),
        ),
    ]
