# Generated by Django 4.0.2 on 2022-06-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0014_device'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
