# Generated by Django 4.0.2 on 2022-10-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0015_delete_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('iPad', 'iPad-Koffer'), ('CR', 'Computerraum'), ('other', 'anderer Raum')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
