# Generated by Django 4.0.2 on 2022-10-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0016_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, choices=[('iPad', 'iPad-Koffer'), ('CR', 'Computerraum'), ('other', 'anderer Raum')], max_length=5),
        ),
    ]
