# Generated by Django 4.1.2 on 2022-12-07 10:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0017_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='alert',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
