# Generated by Django 4.1.5 on 2023-01-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buchungstool', '0018_alter_room_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='series_id',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
